// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtoocgevxdzzovvdsusr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0b29jZ2V2eGR6em92dmRzdXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzE2NjYsImV4cCI6MjA2MjYwNzY2Nn0.KRoNtOBKLIagAENTueApIYFo7Vdlh1iB7lKTiXMn2BM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);